import { Venue, GeneratedItinerary } from '../types/planner.types';
import { GroupDetail } from '../types/group.types';

export const MOCK_USERS = [
  {
    id: 'user_1',
    name: 'Abhishek Jose',
    email: 'abhishek@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1535713875002-d1d0cf377fde?auto=format&fit=crop&w=100&h=100&q=80',
  },
  {
    id: 'user_2',
    name: 'Sarah Chen',
    email: 'sarah.c@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1494790108377-be9c29b29330?auto=format&fit=crop&w=100&h=100&q=80',
  },
  {
    id: 'user_3',
    name: 'Marcus Miller',
    email: 'marcus@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?auto=format&fit=crop&w=100&h=100&q=80',
  },
  {
    id: 'user_4',
    name: 'Pooja Rao',
    email: 'pooja.rao@example.com',
    imageUrl: 'https://images.unsplash.com/photo-1438761681033-6461ffad8d80?auto=format&fit=crop&w=100&h=100&q=80',
  },
];

export const MOCK_GROUPS: GroupDetail[] = [
  {
    id: 'group_koramangala',
    name: 'Koramangala Weekend Outing',
    description: 'Catching up over the weekend, playing games, and having dinner.',
    groupType: 'FRIENDS',
    creatorId: 'user_1',
    inviteCode: 'KORA4390',
    status: 'ACTIVE',
    maxMembers: 10,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 4,
  },
  {
    id: 'group_date',
    name: 'Friday Anniversary Date',
    description: 'Special date night planning.',
    groupType: 'DATE',
    creatorId: 'user_1',
    inviteCode: 'DATE9901',
    status: 'ACTIVE',
    maxMembers: 2,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
    memberCount: 2,
  },
  {
    id: 'group_archived',
    name: 'Past Team Outing',
    description: 'Archived project celebration outing.',
    groupType: 'WORK',
    creatorId: 'user_2',
    inviteCode: 'WORK8832',
    status: 'ARCHIVED',
    maxMembers: 20,
    createdAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 30 * 24 * 60 * 60 * 1000).toISOString(),
    memberCount: 6,
  },
];

export const MOCK_VENUES: Venue[] = [
  {
    id: 'venue_1',
    name: 'Third Wave Coffee Roasters',
    category: 'CAFE',
    rating: 4.6,
    distanceKm: 0.4,
    estimatedCostPerHead: 250,
    openNow: true,
    address: '100 Feet Rd, Koramangala, Bengaluru',
  },
  {
    id: 'venue_2',
    name: 'Toit Beer Co.',
    category: 'RESTAURANT',
    rating: 4.5,
    distanceKm: 4.2,
    estimatedCostPerHead: 900,
    openNow: true,
    address: 'Indiranagar, Bengaluru',
  },
  {
    id: 'venue_3',
    name: 'Cubbon Park',
    category: 'PARK',
    rating: 4.7,
    distanceKm: 5.5,
    estimatedCostPerHead: 0,
    openNow: true,
    address: 'Kasturba Road, Bengaluru',
  },
  {
    id: 'venue_4',
    name: 'Amaaaze Gaming Arcade',
    category: 'ARCADE',
    rating: 4.1,
    distanceKm: 1.2,
    estimatedCostPerHead: 400,
    openNow: true,
    address: '5th Block Koramangala, Bengaluru',
  },
  {
    id: 'venue_5',
    name: 'BluO Bowling Alley',
    category: 'BOWLING',
    rating: 4.3,
    distanceKm: 3.1,
    estimatedCostPerHead: 350,
    openNow: true,
    address: 'Forum Mall, Koramangala, Bengaluru',
  },
  {
    id: 'venue_6',
    name: 'The Escape Hunt',
    category: 'ESCAPE_ROOM',
    rating: 4.6,
    distanceKm: 2.5,
    estimatedCostPerHead: 600,
    openNow: true,
    address: 'Indiranagar, Bengaluru',
  },
  {
    id: 'venue_7',
    name: 'Corner House Ice Creams',
    category: 'DESSERT',
    rating: 4.8,
    distanceKm: 0.3,
    estimatedCostPerHead: 150,
    openNow: true,
    address: 'Koramangala 5th Block, Bengaluru',
  },
];

export const MOCK_PLANS: GeneratedItinerary[] = [
  {
    id: 'plan_chill_bowl',
    name: 'Chill & Bowl',
    tagline: 'A relaxed afternoon with coffee, conversation, and some friendly competition',
    totalEstimatedCostPerHead: 750,
    totalDurationMinutes: 195,
    slots: [
      {
        order: 1,
        venueId: 'venue_1',
        venueName: 'Third Wave Coffee',
        category: 'CAFE',
        arrivalTime: '02:00 PM',
        durationMinutes: 60,
        travelToNextMinutes: 15,
        estimatedCostPerHead: 250,
        note: 'Start here to catch up over coffee and snacks before we head out.',
      },
      {
        order: 2,
        venueId: 'venue_5',
        venueName: 'BluO Bowling Alley',
        category: 'BOWLING',
        arrivalTime: '03:15 PM',
        durationMinutes: 90,
        travelToNextMinutes: 15,
        estimatedCostPerHead: 350,
        note: 'Grab a lane and get competitive! Two rounds of bowling are included.',
      },
      {
        order: 3,
        venueId: 'venue_7',
        venueName: 'Corner House Ice Creams',
        category: 'DESSERT',
        arrivalTime: '05:00 PM',
        durationMinutes: 30,
        travelToNextMinutes: null,
        estimatedCostPerHead: 150,
        note: 'Finish off the afternoon with a famous Death by Chocolate sundae.',
      },
    ],
  },
  {
    id: 'plan_action_packed',
    name: 'Escape & Dine',
    tagline: 'An action-filled outing designed to challenge the brain and reward the stomach',
    totalEstimatedCostPerHead: 1100,
    totalDurationMinutes: 175,
    slots: [
      {
        order: 1,
        venueId: 'venue_6',
        venueName: 'The Escape Hunt',
        category: 'ESCAPE_ROOM',
        arrivalTime: '04:00 PM',
        durationMinutes: 60,
        travelToNextMinutes: 25,
        estimatedCostPerHead: 600,
        note: 'Work together to solve the mystery and escape the room in 60 minutes.',
      },
      {
        order: 2,
        venueId: 'venue_2',
        venueName: 'Toit Beer Co.',
        category: 'RESTAURANT',
        arrivalTime: '05:25 PM',
        durationMinutes: 90,
        travelToNextMinutes: null,
        estimatedCostPerHead: 500,
        note: 'Celebrate your escape with delicious wood-fired pizzas and craft beers.',
      },
    ],
  },
  {
    id: 'plan_budget_friendly',
    name: 'Park Walk & Dessert',
    tagline: 'An affordable outdoor catch up enjoying the evening breeze and fresh air',
    totalEstimatedCostPerHead: 150,
    totalDurationMinutes: 170,
    slots: [
      {
        order: 1,
        venueId: 'venue_3',
        venueName: 'Cubbon Park',
        category: 'PARK',
        arrivalTime: '04:30 PM',
        durationMinutes: 120,
        travelToNextMinutes: 20,
        estimatedCostPerHead: 0,
        note: 'Meet up near the bandstand, take a long walk under the canopy, and enjoy the shade.',
      },
      {
        order: 2,
        venueId: 'venue_7',
        venueName: 'Corner House Ice Creams',
        category: 'DESSERT',
        arrivalTime: '06:50 PM',
        durationMinutes: 30,
        travelToNextMinutes: null,
        estimatedCostPerHead: 150,
        note: 'Cool down with classic scoop ice creams after our long walk.',
      },
    ],
  },
];

export const MOCK_VOTES = {
  plan_chill_bowl: 3,
  plan_action_packed: 1,
  plan_budget_friendly: 0,
};
