import type { AIItineraryResponse, Mood, Place } from '@/types';

const NEVER_INVENT_RULE =
  'NEVER INVENT PLACES. ONLY USE PROVIDED DATA. Do not add, hallucinate, or fabricate any location.';

function jsonOnlyInstruction(): string {
  return 'Return JSON only. No markdown, no prose outside JSON, no code fences.';
}

function stableJson(value: unknown): string {
  return JSON.stringify(value, null, 2);
}

export interface GeneratorAgentPromptInput {
  stops: AIItineraryResponse['stops'];
  total_cost_per_person: number;
  duration_total_mins: number;
  vibe: Mood;
  travel_summary?: AIItineraryResponse['travel_summary'];
}

export interface RetryAgentPromptInput {
  current_itinerary: AIItineraryResponse;
  issues: string[];
  candidate_places: Place[];
  budget: number;
  vibe: Mood;
}

export interface OverseerAgentPromptInput {
  itinerary: AIItineraryResponse;
  per_user_travel?: AIItineraryResponse['member_travel_breakdown'];
  budget: number;
  vibe: Mood;
}

export function buildGeneratorAgentPrompt(input: GeneratorAgentPromptInput): string {
  const payload = {
    stops: input.stops,
    total_cost_per_person: input.total_cost_per_person,
    duration: input.duration_total_mins,
    vibe: input.vibe,
    travel_summary: input.travel_summary || null,
  };

  return [
    'You are refining a real-world itinerary generated by a deterministic system.',
    '',
    'STRICT RULES:',
    '- DO NOT invent, add, or hallucinate any places.',
    '- DO NOT replace places unless explicitly told.',
    '- ONLY work with the provided stops.',
    '- DO NOT change coordinates or locations.',
    '- Keep everything grounded in real data.',
    `- ${NEVER_INVENT_RULE}`,
    '',
    'Your job is to:',
    '1. Improve the flow of the itinerary if needed (reorder stops logically).',
    '2. Ensure the sequence feels natural (start -> main activity -> relax).',
    '3. Generate a short, catchy title for the plan.',
    '4. Write a clear, human-friendly explanation of why this plan works.',
    '',
    'Consider:',
    '- User vibe (chill, fun, romantic, adventure).',
    '- Budget constraints.',
    '- Travel convenience.',
    '- Logical progression of activities.',
    '',
    'INPUT:',
    stableJson(payload),
    '',
    'OUTPUT (JSON ONLY):',
    stableJson({
      title: 'string',
      refined_stops: input.stops,
      why_this_plan: '2-3 sentence explanation',
      flow_summary: 'Place A -> Place B -> Place C',
      issues: ['list minor concerns if present'],
    }),
    '',
    jsonOnlyInstruction(),
  ].join('\n');
}

export function buildRetryAgentPrompt(input: RetryAgentPromptInput): string {
  const payload = {
    current_itinerary: input.current_itinerary,
    issues: input.issues,
    candidate_places: input.candidate_places,
    budget: input.budget,
    vibe: input.vibe,
  };

  return [
    'You are correcting a flawed itinerary from a deterministic planner.',
    '',
    'STRICT RULES:',
    '- You may ONLY use places from the provided candidate pool.',
    '- DO NOT invent new places.',
    '- DO NOT use any external knowledge.',
    '- Maintain realism and coherence.',
    `- ${NEVER_INVENT_RULE}`,
    '',
    'Your job is to:',
    '1. Fix the listed issues.',
    '2. Replace or reorder stops only when necessary.',
    '3. Ensure:',
    '- No repeated type overload (for example, cafe -> cafe -> cafe).',
    '- Logical flow (start -> activity -> relax).',
    '- Budget is respected.',
    '- Travel distances are reasonable.',
    '- Places are socially relevant and hangout-friendly.',
    '',
    'INPUT:',
    stableJson(payload),
    '',
    'OUTPUT (JSON ONLY): return FULL corrected AIItineraryResponse object.',
    'The output must preserve schema fields and corrected stop order/details.',
    stableJson(input.current_itinerary),
    '',
    jsonOnlyInstruction(),
  ].join('\n');
}

export function buildOverseerAgentPrompt(input: OverseerAgentPromptInput): string {
  const payload = {
    itinerary: input.itinerary,
    per_user_travel: input.per_user_travel || null,
    budget: input.budget,
    vibe: input.vibe,
  };

  return [
    'You are a strict evaluator of real-world itineraries.',
    '',
    'Your role is to validate whether an itinerary is realistic, relevant, and high quality.',
    '',
    'STRICT RULES:',
    '- Reject unrealistic, irrelevant, or low-quality plans.',
    '- Be critical and conservative. Do NOT approve weak plans.',
    '- DO NOT modify the itinerary. Only evaluate it.',
    `- ${NEVER_INVENT_RULE}`,
    '',
    'Validation checklist:',
    '1. PLACE VALIDITY:',
    '- Are all stops realistic hangout spots?',
    '- Reject banks, offices, generic buildings, and vague names.',
    '2. FLOW QUALITY:',
    '- Does sequence make practical sense?',
    '- Penalize repetitive patterns (food -> food -> food).',
    '3. TRAVEL FAIRNESS:',
    '- Are travel times reasonable for all users?',
    '- Penalize strong imbalance for any one user.',
    '4. BUDGET:',
    '- Does plan fit within minimum user budget?',
    '5. VIBE MATCH:',
    '- Does the sequence align with intended vibe?',
    '6. SOCIAL RELEVANCE:',
    '- Would people aged about 18-25 realistically choose these stops?',
    '',
    'INPUT:',
    stableJson(payload),
    '',
    'OUTPUT (JSON ONLY):',
    stableJson({
      valid: true,
      score: 0.0,
      verdict: 'accept',
      issues: ['list of problems'],
      summary: 'short explanation of evaluation',
    }),
    '',
    'Score guidance:',
    '- 0.85-1.00: strong and realistic',
    '- 0.65-0.84: acceptable with minor concerns',
    '- < 0.65: reject',
    '',
    jsonOnlyInstruction(),
  ].join('\n');
}

export const GROQ_PIPELINE_CHAIN_NOTE = [
  'Deterministic Engine',
  '  -> Overseer (validate)',
  '  -> IF rejected: Retry (correct)',
  '  -> Overseer again',
  '  -> Final output',
  '',
  NEVER_INVENT_RULE,
].join('\n');
